server:
  port: ${SERVER_PORT:8000}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

spring:
  cloud:
    gateway:
      routes: []

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    com.sparta.gateway: INFO
