spring:
  application:
    name: gateway-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  instance:
    prefer-ip-address: true

gateway:
  openapi:
    services:
      - auth-service
      - chat-service

security:
  jwt:
    enabled: ${SECURITY_JWT_ENABLED:false}

springdoc:
  swagger-ui:
    operations-sorter: method
