package com.sparta.gateway.config;

import org.springframework.http.HttpHeaders;
import org.springframework.util.StringUtils;
import org.springframework.web.server.ServerWebExchange;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;

/**
 * Rewrites OpenAPI {@code servers} so Swagger "Try it out" targets the
 * public Gateway URL ({@code http(s)://host/{service}}) instead of the
 * Docker-internal address generated by each microservice.
 */
final class OpenApiServersRewriter {

	static final String REWRITE_ATTR = OpenApiServersRewriter.class.getName() + ".rewrite";

	private OpenApiServersRewriter() {
	}

	static String resolveGatewayServiceUrl(ServerWebExchange exchange, String service) {
		HttpHeaders headers = exchange.getRequest().getHeaders();

		String proto = firstHeaderValue(headers, "X-Forwarded-Proto");
		if (!StringUtils.hasText(proto)) {
			proto = exchange.getRequest().getURI().getScheme();
		}
		if (!StringUtils.hasText(proto)) {
			proto = "http";
		}

		String host = firstHeaderValue(headers, "X-Forwarded-Host");
		if (!StringUtils.hasText(host)) {
			host = headers.getFirst(HttpHeaders.HOST);
		}
		if (!StringUtils.hasText(host)) {
			host = exchange.getRequest().getURI().getAuthority();
		}

		return proto + "://" + host + "/" + service;
	}

	static String rewriteServers(ObjectMapper objectMapper, String body, String serverUrl) throws Exception {
		JsonNode root = objectMapper.readTree(body);
		if (!(root instanceof ObjectNode objectNode)) {
			return body;
		}

		ArrayNode servers = objectMapper.createArrayNode();
		ObjectNode server = objectMapper.createObjectNode();
		server.put("url", serverUrl);
		server.put("description", "Via API Gateway");
		servers.add(server);
		objectNode.set("servers", servers);
		return objectMapper.writeValueAsString(objectNode);
	}

	private static String firstHeaderValue(HttpHeaders headers, String name) {
		String raw = headers.getFirst(name);
		if (!StringUtils.hasText(raw)) {
			return null;
		}
		return raw.split(",")[0].trim();
	}
}
